- name: Atualizar cache
  apt:
      update_cache: yes
      cache_valid_time: 3600
  become: yes

- name: Atualizar pacotes
  apt:
      upgrade: dist
  become: yes

- name: Instala pacotes diários
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - flake8
    - tig
    - glances
    - htop
    - vlc
    - browser-plugin-vlc
    - sqlite3
    - curl
    - vim-nox
    - lm-sensors
