- name: Instalar o pip3
  apt:
    name: python3-pip
    state: latest
  become: yes

- name: Instalar virtualenv
  command: pip3 install virtualenv

- name: Instalar toggl-client
  command: pip3 install toggl-client

- name: Deixa tgc disponivel globalmente
  file:
    src: /home/lramosduarte/.local/bin/tgc
    path: /usr/local/bin/tgc
    state: link
  become: yes