- name: Instalar o pip3
  apt:
    name: python3-pip
    state: latest
  become: yes

- name: Instalar virtualenv
  command: pip install virtualenv

- name: Instalar toggl-client
  command: pip install toggl-client
