- name: Instalar o ssh
  become: yes
  apt:
    name: openssh-server
    state: present

- name: Cria uma chave ssh para uso genérico
  shell : mkdir $HOME/.ssh 
  become: yes  

- name: Configura o ssh config para projetos pessoais usarem a chave pessoal
  template:
    src: templates/config.j2
    dest: $HOME/.ssh/config
