- name: Instalar o git
  become: yes
  apt:
    name: git
    state: present

- name: Configura o git
  template:
    src: templates/.gitconfig.j2
    dest: $HOME/.gitconfig

- name: Configura o gitignore global
  template:
    src: templates/.gitignore.j2
    dest: $HOME/.gitignore