- name: Baixa o atom.deb pelo endpoint da ultima versão estável
  get_url:
    url: https://atom.io/download/deb
    dest: /tmp/

- name: Instala o atom
  become: yes
  apt:
    deb: /tmp/atom-amd64.deb

- name: Instala o pacote sync-settings
  command: apm install sync-settings

- name: Configura o sync-settings
  template:
    src: templates/config.cson.j2
    dest: $HOME/.atom/config.cson
